version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rubezhbot
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - rubezhbot_logs:/app/logs
    restart: unless-stopped

volumes:
  rubezhbot_logs:
    
networks:
  default:
    driver: bridge
